# Generated by Django 3.2 on 2021-04-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='push',
            old_name='body',
            new_name='booty',
        ),
        migrations.RemoveField(
            model_name='push',
            name='array',
        ),
    ]
