# Generated by Django 3.2 on 2021-04-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0002_auto_20210422_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='array',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='push',
            old_name='booty',
            new_name='push',
        ),
        migrations.RenameField(
            model_name='push',
            old_name='author',
            new_name='user',
        ),
    ]
