# Generated by Django 3.2 on 2021-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genderpronouns',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aboutme',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
