# Generated by Django 3.2 on 2021-04-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0005_auto_20210423_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='array',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push', to='codrs.array'),
        ),
        migrations.AlterField(
            model_name='array',
            name='body',
            field=models.CharField(default='body', max_length=3000),
        ),
        migrations.AlterField(
            model_name='array',
            name='user',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='push',
            name='push',
            field=models.CharField(default='push', max_length=1000),
        ),
        migrations.AlterField(
            model_name='push',
            name='user',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
