# Generated by Django 3.2 on 2021-04-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0008_alter_push_array'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='push',
            unique_together={('user', 'push')},
        ),
    ]
