# Generated by Django 3.2 on 2021-04-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0009_alter_push_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='push',
            unique_together=set(),
        ),
    ]
