# Generated by Django 3.2 on 2021-04-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codrs', '0010_alter_push_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=100)),
                ('comment', models.CharField(default='comment', max_length=1000)),
                ('array', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='codrs.array')),
            ],
        ),
        migrations.DeleteModel(
            name='Push',
        ),
    ]
